name: Deploy on24.motisan.info
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.STAGING_SERVER }}
          username: ${{ secrets.STAGING_USERNAME }}
          password: ${{ secrets.STAGING_PASSWORD }}
          server-dir: /
          local-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/data/**
            **/config/**
            **/config.local.php
      - name: Fix permissions
        run: |
          lftp -u "${{ secrets.STAGING_USERNAME }}","${{ secrets.STAGING_PASSWORD }}" ftp://${{ secrets.STAGING_SERVER }} << 'EOF'
          find / -type d -exec chmod 755 {} \;
          find / -type f -exec chmod 644 {} \;
          bye
          EOF
